[2025-05-25T05:30:35.143+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:30:35.376+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-05-25T05:30:35.504+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-02-28T00:00:00+00:00 [queued]>
[2025-05-25T05:30:35.511+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:30:35.933+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_file> on 2025-02-28 00:00:00+00:00
[2025-05-25T05:30:36.175+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:30:36.208+0000] {standard_task_runner.py:72} INFO - Started process 1190 to run task
[2025-05-25T05:30:36.512+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'generate_file', 'scheduled__2025-02-28T00:00:00+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmp98q4zwl4']
[2025-05-25T05:30:36.549+0000] {standard_task_runner.py:105} INFO - Job 167: Subtask generate_file
[2025-05-25T05:30:39.825+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.generate_file scheduled__2025-02-28T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:30:41.507+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='generate_file' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T00:00:00+00:00'
[2025-05-25T05:30:41.524+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:30:43.011+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-25T05:30:43.092+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:30:43.100+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=generate_file, run_id=scheduled__2025-02-28T00:00:00+00:00, execution_date=20250228T000000, start_date=20250525T053035, end_date=20250525T053043
[2025-05-25T05:30:47.100+0000] {job.py:229} INFO - Heartbeat recovered after 13.45 seconds
[2025-05-25T05:30:47.211+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:30:47.460+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-25T05:30:47.489+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
