[2025-06-10T15:45:01.882+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:45:01.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:45:02.060+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:45:02.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:45:05.719+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:45:05.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:45:05.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:45:06.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 5.317 seconds
[2025-06-10T15:45:39.088+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:45:39.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:45:39.152+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:45:39.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:45:39.751+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:45:39.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:45:39.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:45:40.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 1.069 seconds
[2025-06-10T15:46:12.026+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:46:12.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:46:12.231+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:46:12.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:46:12.967+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:46:12.953+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:46:12.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:46:14.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 2.316 seconds
[2025-06-10T15:46:45.380+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:46:45.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:46:45.445+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:46:45.444+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:46:45.895+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:46:45.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:46:45.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:46:46.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.811 seconds
[2025-06-10T15:47:17.938+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:47:17.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:47:18.035+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:47:18.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:47:18.717+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:47:18.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:47:18.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:47:18.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 1.154 seconds
[2025-06-10T15:47:51.371+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:47:51.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:47:51.560+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:47:51.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:47:53.308+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:47:53.293+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:47:53.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:47:53.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 2.342 seconds
[2025-06-10T15:48:24.431+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:48:24.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:48:24.453+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:48:24.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:48:24.547+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:48:24.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:48:24.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:48:24.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.284 seconds
[2025-06-10T15:48:55.537+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:48:55.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:48:55.557+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:48:55.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:48:55.612+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:48:55.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:48:55.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:48:55.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.155 seconds
[2025-06-10T15:49:26.284+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:49:26.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:49:26.322+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:49:26.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:49:26.552+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:49:26.548+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:49:26.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:49:26.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.378 seconds
[2025-06-10T15:49:57.237+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:49:57.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:49:57.251+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:49:57.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:49:57.312+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:49:57.309+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:49:57.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:49:57.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.148 seconds
[2025-06-10T15:50:27.978+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:50:27.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:50:27.994+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:50:27.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:50:28.067+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:50:28.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:50:28.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:50:28.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.292 seconds
[2025-06-10T15:50:58.526+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:50:58.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:50:58.535+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:50:58.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:50:58.592+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:50:58.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:50:58.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:50:58.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.146 seconds
[2025-06-10T15:51:28.843+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:51:28.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:51:28.854+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:51:28.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:51:28.894+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:51:28.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:51:28.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:51:28.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.128 seconds
[2025-06-10T15:52:01.048+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:52:01.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:52:01.089+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:52:01.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:52:01.530+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:52:01.526+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:52:01.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:52:01.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.653 seconds
[2025-06-10T15:52:32.148+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:52:32.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:52:32.161+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:52:32.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:52:32.204+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:52:32.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:52:32.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:52:32.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.132 seconds
[2025-06-10T15:53:03.108+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:53:03.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:53:03.117+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:53:03.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:53:03.167+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:53:03.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:53:03.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:53:03.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.118 seconds
[2025-06-10T15:53:33.478+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:53:33.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:53:33.509+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:53:33.507+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:53:33.591+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:53:33.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:53:33.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:53:33.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.217 seconds
[2025-06-10T15:54:03.870+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:54:03.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:54:03.881+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:54:03.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:54:03.940+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:54:03.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:54:03.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:54:04.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.151 seconds
[2025-06-10T15:54:34.728+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:54:34.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:54:34.741+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:54:34.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:54:34.800+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:54:34.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:54:34.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:54:34.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.181 seconds
[2025-06-10T15:55:05.314+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:55:05.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:55:05.340+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:55:05.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:55:05.451+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:55:05.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:55:05.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:55:05.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.298 seconds
[2025-06-10T15:55:36.248+0000] {processor.py:186} INFO - Started process (PID=315) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:55:36.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:55:36.277+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:55:36.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:55:36.482+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:55:36.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:55:36.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:55:36.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.385 seconds
[2025-06-10T15:56:06.759+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:56:06.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:56:06.775+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:56:06.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:56:06.859+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:56:06.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:56:06.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:56:06.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.194 seconds
[2025-06-10T15:56:38.054+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:56:38.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:56:38.068+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:56:38.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:56:38.163+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:56:38.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:56:38.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:56:38.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.224 seconds
[2025-06-10T15:57:08.767+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:57:08.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:57:08.777+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:57:08.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:57:08.821+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:57:08.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:57:08.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:57:08.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.127 seconds
[2025-06-10T15:57:39.114+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:57:39.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:57:39.125+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:57:39.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:57:39.207+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:57:39.204+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:57:39.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:57:39.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.184 seconds
[2025-06-10T15:58:09.612+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:58:09.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:58:09.662+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:58:09.653+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:58:09.737+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:58:09.731+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:58:09.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:58:09.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.329 seconds
[2025-06-10T15:58:40.922+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:58:40.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:58:40.939+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:58:40.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:58:41.009+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:58:41.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 13
    schedule_interval='*/1 * * * *'
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-06-10T15:58:41.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:58:41.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.231 seconds
[2025-06-10T15:59:08.876+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:59:08.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:59:08.903+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:59:08.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:59:09.487+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:59:09.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T15:59:09.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:59:09.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.803 seconds
[2025-06-10T15:59:40.046+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:59:40.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T15:59:40.062+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:59:40.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:59:40.137+0000] {logging_mixin.py:190} INFO - [2025-06-10T15:59:40.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T15:59:40.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T15:59:40.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.195 seconds
[2025-06-10T16:00:10.480+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:00:10.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T16:00:10.489+0000] {logging_mixin.py:190} INFO - [2025-06-10T16:00:10.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:00:10.547+0000] {logging_mixin.py:190} INFO - [2025-06-10T16:00:10.534+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T16:00:10.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:00:10.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.142 seconds
[2025-06-10T16:00:41.673+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:00:41.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T16:00:41.685+0000] {logging_mixin.py:190} INFO - [2025-06-10T16:00:41.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:00:41.768+0000] {logging_mixin.py:190} INFO - [2025-06-10T16:00:41.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T16:00:41.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:00:41.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.208 seconds
[2025-06-10T16:01:12.464+0000] {processor.py:186} INFO - Started process (PID=448) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:01:12.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T16:01:12.488+0000] {logging_mixin.py:190} INFO - [2025-06-10T16:01:12.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:01:12.601+0000] {logging_mixin.py:190} INFO - [2025-06-10T16:01:12.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T16:01:12.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:01:12.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.508 seconds
[2025-06-10T16:01:44.127+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:01:44.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T16:01:44.138+0000] {logging_mixin.py:190} INFO - [2025-06-10T16:01:44.137+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:01:44.209+0000] {logging_mixin.py:190} INFO - [2025-06-10T16:01:44.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T16:01:44.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T16:01:44.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.262 seconds
[2025-06-10T18:44:22.591+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:44:22.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:44:22.692+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:44:22.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:44:23.847+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:44:23.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:44:23.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:44:23.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 2.129 seconds
[2025-06-10T18:44:54.794+0000] {processor.py:186} INFO - Started process (PID=482) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:44:54.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:44:54.912+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:44:54.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:44:55.423+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:44:55.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:44:55.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:44:55.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 1.158 seconds
[2025-06-10T18:48:42.200+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:48:42.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:48:42.229+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:48:42.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:48:42.751+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:48:42.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:48:42.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:48:43.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 1.136 seconds
[2025-06-10T18:49:16.003+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:49:16.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:49:16.137+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:49:16.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:49:19.095+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:49:18.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:49:19.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:49:19.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 3.915 seconds
[2025-06-10T18:49:53.156+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:49:53.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:49:53.370+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:49:53.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:49:55.380+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:49:55.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:49:55.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:49:56.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 3.026 seconds
[2025-06-10T18:50:28.686+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:50:28.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:50:28.773+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:50:28.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:50:29.152+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:50:29.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:50:29.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:50:29.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.975 seconds
[2025-06-10T18:51:00.289+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:51:00.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:51:00.297+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:51:00.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:51:00.348+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:51:00.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:51:00.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:51:00.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.128 seconds
[2025-06-10T18:51:30.872+0000] {processor.py:186} INFO - Started process (PID=141) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:51:30.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:51:30.880+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:51:30.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:51:30.934+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:51:30.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:51:30.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:51:30.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.128 seconds
[2025-06-10T18:52:01.360+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:52:01.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:52:01.375+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:52:01.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:52:01.431+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:52:01.417+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:52:01.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:52:01.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.162 seconds
[2025-06-10T18:52:32.946+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:52:32.951+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:52:32.979+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:52:32.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:52:33.070+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:52:33.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:52:33.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:52:33.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.317 seconds
[2025-06-10T18:53:03.642+0000] {processor.py:186} INFO - Started process (PID=178) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:53:03.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:53:03.653+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:53:03.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:53:03.790+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:53:03.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:53:03.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:53:03.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.253 seconds
[2025-06-10T18:53:34.300+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:53:34.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:53:34.331+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:53:34.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:53:34.467+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:53:34.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:53:34.485+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:53:34.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.458 seconds
[2025-06-10T18:54:05.297+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:54:05.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:54:05.320+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:54:05.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:54:05.650+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:54:05.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:54:05.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:54:05.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.459 seconds
[2025-06-10T18:54:36.553+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:54:36.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:54:36.563+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:54:36.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:54:36.624+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:54:36.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:54:36.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:54:36.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.158 seconds
[2025-06-10T18:55:07.403+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:55:07.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:55:07.414+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:55:07.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:55:07.479+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:55:07.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:55:07.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:55:07.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.171 seconds
[2025-06-10T18:55:38.182+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:55:38.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:55:38.197+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:55:38.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:55:38.426+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:55:38.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:55:38.436+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:55:38.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.386 seconds
[2025-06-10T18:56:08.765+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:56:08.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:56:08.784+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:56:08.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:56:08.843+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:56:08.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:56:08.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:56:08.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.209 seconds
[2025-06-10T18:56:39.109+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:56:39.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:56:39.121+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:56:39.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:56:39.187+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:56:39.169+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:56:39.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:56:39.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.172 seconds
[2025-06-10T18:57:09.737+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:57:09.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:57:09.749+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:57:09.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:57:09.803+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:57:09.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:57:09.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:57:09.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.183 seconds
[2025-06-10T18:57:40.138+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:57:40.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:57:40.150+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:57:40.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:57:40.202+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:57:40.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:57:40.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:57:40.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.148 seconds
[2025-06-10T18:58:10.550+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:58:10.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:58:10.565+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:58:10.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:58:10.736+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:58:10.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:58:10.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:58:10.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.423 seconds
[2025-06-10T18:58:41.384+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:58:41.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:58:41.416+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:58:41.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:58:41.503+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:58:41.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:58:41.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:58:41.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.270 seconds
[2025-06-10T18:59:12.626+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:59:12.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:59:12.636+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:59:12.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:59:12.700+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:59:12.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:59:12.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:59:12.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.148 seconds
[2025-06-10T18:59:43.558+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:59:43.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T18:59:43.571+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:59:43.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:59:43.635+0000] {logging_mixin.py:190} INFO - [2025-06-10T18:59:43.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T18:59:43.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T18:59:43.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.159 seconds
[2025-06-10T19:00:13.863+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:00:13.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:00:13.872+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:00:13.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:00:13.934+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:00:13.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:00:13.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:00:13.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.145 seconds
[2025-06-10T19:00:44.700+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:00:44.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:00:44.726+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:00:44.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:00:45.052+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:00:44.968+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:00:45.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:00:45.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.583 seconds
[2025-06-10T19:01:15.928+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:01:15.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:01:15.952+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:01:15.951+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:01:16.493+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:01:16.354+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:01:16.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:01:16.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.821 seconds
[2025-06-10T19:01:47.291+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:01:47.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:01:47.304+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:01:47.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:01:47.358+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:01:47.347+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:01:47.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:01:47.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.160 seconds
[2025-06-10T19:02:17.739+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:02:17.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:02:17.753+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:02:17.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:02:17.812+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:02:17.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:02:17.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:02:17.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.162 seconds
[2025-06-10T19:02:48.164+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:02:48.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:02:48.179+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:02:48.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:02:48.269+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:02:48.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:02:48.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:02:48.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.209 seconds
[2025-06-10T19:03:19.053+0000] {processor.py:186} INFO - Started process (PID=402) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:03:19.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:03:19.068+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:03:19.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:03:19.119+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:03:19.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:03:19.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:03:19.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.168 seconds
[2025-06-10T19:03:49.479+0000] {processor.py:186} INFO - Started process (PID=413) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:03:49.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:03:49.502+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:03:49.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:03:49.613+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:03:49.601+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:03:49.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:03:49.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.237 seconds
[2025-06-10T19:04:19.945+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:04:19.948+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:04:19.958+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:04:19.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:04:20.027+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:04:20.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:04:20.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:04:20.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.167 seconds
[2025-06-10T19:04:50.926+0000] {processor.py:186} INFO - Started process (PID=435) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:04:50.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:04:50.936+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:04:50.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:04:50.996+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:04:50.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:04:51.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:04:51.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.162 seconds
[2025-06-10T19:05:21.403+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:05:21.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:05:21.419+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:05:21.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:05:21.483+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:05:21.473+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:05:21.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:05:21.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.222 seconds
[2025-06-10T19:05:53.473+0000] {processor.py:186} INFO - Started process (PID=456) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:05:53.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:05:53.514+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:05:53.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:05:53.924+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:05:53.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:05:53.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:05:54.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.730 seconds
[2025-06-10T19:06:25.164+0000] {processor.py:186} INFO - Started process (PID=467) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:06:25.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:06:25.173+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:06:25.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:06:25.223+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:06:25.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:06:25.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:06:25.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.124 seconds
[2025-06-10T19:06:55.711+0000] {processor.py:186} INFO - Started process (PID=479) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:06:55.733+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:06:55.757+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:06:55.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:06:56.128+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:06:56.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:06:56.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:06:56.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.527 seconds
[2025-06-10T19:07:26.724+0000] {processor.py:186} INFO - Started process (PID=497) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:07:26.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:07:26.741+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:07:26.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:07:26.804+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:07:26.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:07:26.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:07:26.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.236 seconds
[2025-06-10T19:07:57.271+0000] {processor.py:186} INFO - Started process (PID=507) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:07:57.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:07:57.280+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:07:57.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:07:57.335+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:07:57.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:07:57.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:07:57.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.149 seconds
[2025-06-10T19:08:28.289+0000] {processor.py:186} INFO - Started process (PID=518) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:08:28.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:08:28.304+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:08:28.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:08:28.388+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:08:28.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:08:28.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:08:28.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.203 seconds
[2025-06-10T19:08:59.871+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:08:59.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:08:59.921+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:08:59.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:09:00.104+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:09:00.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:09:00.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:09:00.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.596 seconds
[2025-06-10T19:09:31.201+0000] {processor.py:186} INFO - Started process (PID=541) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:09:31.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:09:31.228+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:09:31.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:09:31.403+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:09:31.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:09:31.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:09:31.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.326 seconds
[2025-06-10T19:10:02.182+0000] {processor.py:186} INFO - Started process (PID=552) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:10:02.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:10:02.237+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:10:02.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:10:02.506+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:10:02.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:10:02.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:10:02.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.474 seconds
[2025-06-10T19:10:33.447+0000] {processor.py:186} INFO - Started process (PID=563) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:10:33.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:10:33.460+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:10:33.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:10:33.580+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:10:33.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:10:33.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:10:33.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.348 seconds
[2025-06-10T19:11:04.493+0000] {processor.py:186} INFO - Started process (PID=574) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:11:04.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:11:04.501+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:11:04.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:11:04.557+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:11:04.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:11:04.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:11:04.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.123 seconds
[2025-06-10T19:11:34.900+0000] {processor.py:186} INFO - Started process (PID=585) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:11:34.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:11:34.913+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:11:34.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:11:34.974+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:11:34.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:11:34.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:11:35.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.220 seconds
[2025-06-10T19:12:05.617+0000] {processor.py:186} INFO - Started process (PID=597) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:12:05.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:12:05.633+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:12:05.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:12:05.812+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:12:05.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:12:05.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:12:06.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.472 seconds
[2025-06-10T19:12:36.798+0000] {processor.py:186} INFO - Started process (PID=608) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:12:36.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:12:36.810+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:12:36.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:12:36.876+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:12:36.865+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:12:36.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:12:36.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.162 seconds
[2025-06-10T19:13:08.721+0000] {processor.py:186} INFO - Started process (PID=619) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:13:08.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:13:08.839+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:13:08.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:13:10.188+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:13:09.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:13:10.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:13:10.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 1.804 seconds
[2025-06-10T19:13:51.458+0000] {processor.py:186} INFO - Started process (PID=636) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:13:51.529+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:13:51.655+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:13:51.653+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:13:52.042+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:13:51.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:13:52.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:13:52.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 2.615 seconds
[2025-06-10T19:14:32.939+0000] {processor.py:186} INFO - Started process (PID=647) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:14:32.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:14:32.998+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:14:32.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:14:34.341+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:14:34.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:14:34.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:14:34.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 1.813 seconds
[2025-06-10T19:15:06.176+0000] {processor.py:186} INFO - Started process (PID=664) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:15:06.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:15:06.242+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:15:06.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:15:06.357+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:15:06.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:15:06.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:15:06.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.394 seconds
[2025-06-10T19:15:37.514+0000] {processor.py:186} INFO - Started process (PID=673) to work on /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:15:37.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_stream_synth.py for tasks to queue
[2025-06-10T19:15:37.557+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:15:37.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:15:37.820+0000] {logging_mixin.py:190} INFO - [2025-06-10T19:15:37.780+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_stream_synth.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_stream_synth.py", line 4, in <module>
    import faker
ModuleNotFoundError: No module named 'faker'
[2025-06-10T19:15:37.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_stream_synth.py
[2025-06-10T19:15:38.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_stream_synth.py took 0.536 seconds
