[2025-05-25T05:31:30.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-25T05:31:30.435+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-03-04T00:00:00+00:00 [queued]>
[2025-05-25T05:31:30.518+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_file_to_psql.generate_file scheduled__2025-03-04T00:00:00+00:00 [queued]>
[2025-05-25T05:31:30.521+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-25T05:31:31.518+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_file> on 2025-03-04 00:00:00+00:00
[2025-05-25T05:31:31.625+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1236) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T05:31:31.772+0000] {standard_task_runner.py:72} INFO - Started process 1267 to run task
[2025-05-25T05:31:31.706+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_file_to_psql', 'generate_file', 'scheduled__2025-03-04T00:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/data_quality.py', '--cfg-path', '/tmp/tmpatu0dyiu']
[2025-05-25T05:31:31.856+0000] {standard_task_runner.py:105} INFO - Job 180: Subtask generate_file
[2025-05-25T05:31:37.237+0000] {task_command.py:467} INFO - Running <TaskInstance: load_file_to_psql.generate_file scheduled__2025-03-04T00:00:00+00:00 [running]> on host b4cf172ed0b9
[2025-05-25T05:31:38.840+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='https://t.me/Shust_DE' AIRFLOW_CTX_DAG_OWNER='@Shust_DE' AIRFLOW_CTX_DAG_ID='load_file_to_psql' AIRFLOW_CTX_TASK_ID='generate_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T00:00:00+00:00'
[2025-05-25T05:31:38.856+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-25T05:31:39.315+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-25T05:31:39.619+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-25T05:31:39.636+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_file_to_psql, task_id=generate_file, run_id=scheduled__2025-03-04T00:00:00+00:00, execution_date=20250304T000000, start_date=20250525T053130, end_date=20250525T053139
[2025-05-25T05:31:41.620+0000] {job.py:229} INFO - Heartbeat recovered after 11.88 seconds
[2025-05-25T05:31:41.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-25T05:31:41.962+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-05-25T05:31:42.031+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-25T05:31:42.064+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
